function createcontour(xdata1, ydata1, zdata1)
%CREATECONTOUR(xdata1, ydata1, zdata1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 20-Sep-2023 23:26:50

% Create contour
contour(xdata1,ydata1,zdata1,'LineWidth',2,'LevelList',[-6 -3]);

